apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: k8s-emad-128768042813-dev-apps
    newName: 128768042813.dkr.ecr.us-east-1.amazonaws.com/k8s-emad-128768042813-tomcat
    newTag: 20260501-1655-087117b
  - name: k8s-emad-128768042813-dev-rabbitmq
    newName: 128768042813.dkr.ecr.us-east-1.amazonaws.com/k8s-emad-128768042813-rabbitmq
    newTag: latest
  - name: k8s-emad-128768042813-dev-memcached
    newName: 128768042813.dkr.ecr.us-east-1.amazonaws.com/k8s-emad-128768042813-memcached
    newTag: latest
  - name: k8s-emad-128768042813-dev-mysql
    newName: 128768042813.dkr.ecr.us-east-1.amazonaws.com/k8s-emad-128768042813-mysql
    newTag: latest
